# Generated by Django 4.1.1 on 2022-09-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
